// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUB-86_0QwnxAe-mb0mg2EVtCk1pQ2QRY',
    appId: '1:192698496915:web:9e6abe7de3572a414e9a66',
    messagingSenderId: '192698496915',
    projectId: 'purificador-5b112',
    authDomain: 'purificador-5b112.firebaseapp.com',
    databaseURL: 'https://purificador-5b112-default-rtdb.firebaseio.com',
    storageBucket: 'purificador-5b112.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC48LNJjoac7f_OyGo-5tqBS9NMKgC7RvU',
    appId: '1:192698496915:android:b7f082afbf30c9994e9a66',
    messagingSenderId: '192698496915',
    projectId: 'purificador-5b112',
    databaseURL: 'https://purificador-5b112-default-rtdb.firebaseio.com',
    storageBucket: 'purificador-5b112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABXwh9uK9fUG0_IKRiZn-DBYzlN61uWMM',
    appId: '1:192698496915:ios:8232c4e3b9e6a11d4e9a66',
    messagingSenderId: '192698496915',
    projectId: 'purificador-5b112',
    databaseURL: 'https://purificador-5b112-default-rtdb.firebaseio.com',
    storageBucket: 'purificador-5b112.firebasestorage.app',
    iosBundleId: 'com.example.purifier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABXwh9uK9fUG0_IKRiZn-DBYzlN61uWMM',
    appId: '1:192698496915:ios:8232c4e3b9e6a11d4e9a66',
    messagingSenderId: '192698496915',
    projectId: 'purificador-5b112',
    databaseURL: 'https://purificador-5b112-default-rtdb.firebaseio.com',
    storageBucket: 'purificador-5b112.firebasestorage.app',
    iosBundleId: 'com.example.purifier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUB-86_0QwnxAe-mb0mg2EVtCk1pQ2QRY',
    appId: '1:192698496915:web:feda5a793f702b664e9a66',
    messagingSenderId: '192698496915',
    projectId: 'purificador-5b112',
    authDomain: 'purificador-5b112.firebaseapp.com',
    databaseURL: 'https://purificador-5b112-default-rtdb.firebaseio.com',
    storageBucket: 'purificador-5b112.firebasestorage.app',
  );

}